import React, { useState } from 'react';
import Head from 'next/head';
import { fetchUsers } from '@hooks/useUsers';
import styles from '@styles/Admin.module.css';
import { User } from '../components/admin/user';

export default function Admin() {
	const [url, setUrl] = useState('/api/user/getUsers');
	const [updating, setUpdating] = useState(false);


	const [data, isLoading, error] = fetchUsers(url, updating);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.players}>
				{error ? (
					<p>There has been a server issue.</p>
				) : (
					data.map((user, i) => <User key={`${user._id}-${i}`} updating={updating} setUpdating={setUpdating} user={user} />)
				)}
			</main>
		</>
	);
}
