import Head from "next/head";
import UseAddUser from "@hooks/addUser";
import { useState } from "react";

export default function Home() {
	const [name, setName] = useState("");
	const [email, setEmail] = useState("");
	const [password, setPassword] = useState("");

	const [addUser, isLoading, error] = UseAddUser(null);

	const saveUser = async (event) => {
		event.preventDefault();

		const newUser = {
			name,
			email,
			password,
		};
		addUser(newUser);
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<form onSubmit={saveUser}>
					<label>
						<input
							type="text"
							placeholder="Full Name"
							onChange={(event) => setName(event.target.name)}
						/>
					</label>
					<label>
						<input
							type="text"
							placeholder="Email"
							onChange={(event) => setName(event.target.email)}
						/>
					</label>
					<label>
						<input
							type="text"
							placeholder="Password"
							onChange={(event) => setName(event.target.password)}
						/>
					</label>
					<input type="submit" disabled={isLoading} />
				</form>
			</main>
		</>
	);
}
