import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import {getMembers} from '../hooks/useMongoDB';
import User from '../models/user'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const insertDocument = useInsertDocument('myCollection');
  // const [formData, setFormData] = useState({name: 'Ron', email: 'ron@gmail.com'});
  // const [members, error] = getMembers();


  console.log(getMembers())

  // const handleEvent = async (event) => {
  //   event.preventDefault()
  //   const res = await fetch('/api/user/find', {
  //     method: 'POST',
  //     headers: { 'Content-Type': 'application/json' },
  //     body: JSON.stringify(formData),
  //   })
  //   // handle the response from the server
  // }

    // try {
    //   await insertDocument(newDocument);
    //   console.log('Document saved successfully');
    // } catch (err) {
    //   console.error('Failed to save document', err);
    // }
    // console.log(db);
    

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <button onClick={handleEvent}>Add Client</button> */}

      </main>
    </>
  )
}
