import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import useMongoDB from '@/hooks/useMongoDB'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const insertDocument = useInsertDocument('myCollection');
  const [db, error] = useMongoDB();

  async function handleEvent (e){
    e.preventDefault();

    const newDocument = {
      name: "badr",
      email: "bmorsadi@gmail.com",
      password: "1234",
    };

    // try {
    //   await insertDocument(newDocument);
    //   console.log('Document saved successfully');
    // } catch (err) {
    //   console.error('Failed to save document', err);
    // }
    console.log(db);
    
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

      <button onClick={handleEvent}>Add Client</button>
      </main>
    </>
  )
}
