import Head from 'next/head';
import Membership from '@components/membership';
import { useState } from 'react';

export default function Join() {
	
	return (
		<>
			<Head>
				<title>Subscribe to The Team</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Membership />
		</>
	);
}
