import React, { useState } from 'react';
import Head from 'next/head';
import styles from '@styles/Membership.module.css';
import { usePlayers } from '@hooks/players';
import { useEffect } from 'react';

export default function Membership() {
	const { getUsers, addUser, data, isLoading, message } = usePlayers();
	const [firstName, setFirstName] = useState('');
	const [lastName, setLastName] = useState('');
	const [email, setEmail] = useState('');
	const [level, setLevel] = useState('');
	const [referrer, setReferrer] = useState('');

	console.log('test')

	const saveUser = async (event) => {
		event.preventDefault();

		const newPlayer = {
			firstName,
			lastName,
			email,
			level,
			referrer,
		};

		await addUser(newPlayer);

		setFirstName('');
		setLastName('');
		setEmail('');
		setLevel('');
		setReferrer('');
	};

	useEffect(() => {
		getUsers();
	}, []);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.register}>
				<p>players in the Team: {data.length}</p>
				<form name='' onSubmit={saveUser}>
					<label>
						<input
							type='text'
							placeholder='First Name'
							value={firstName}
							onChange={(event) => setFirstName(event.target.value)}
							required
						/>
					</label>
					<label>
						<input
							type='text'
							placeholder='Last Name'
							value={lastName}
							onChange={(event) => setLastName(event.target.value)}
							required
						/>
					</label>
					<label>
						<input
							type='email'
							placeholder='Email'
							value={email}
							onChange={(event) => setEmail(event.target.value)}
							required
						/>
					</label>
					<label>
						<input
							type='number'
							placeholder='level'
							step='.5'
							value={level}
							onChange={(event) => setLevel(event.target.value)}
							required
						/>
					</label>
					<label>
						<input type='text' value={referrer} placeholder='Referrer' onChange={(event) => setReferrer(event.target.value)} />
					</label>
					<input type='submit' disabled={isLoading} />
				</form>
				{message?.message && <p>{message?.message}</p>}
			</main>
		</>
	);
}
